### PR TITLE
Update composer

### PR DESCRIPTION
**Pull request by derschatta**
Udpated composer.lock file by running `composer update`.

This gets rid of the deprecated warning when running on newer versions of PHP (e.g. 8.1).

### CODE REVIEW

**Comment by codyfinegan** [comment]
@derschatta  - This change drops out 5.6 install support (7.0+ can be installed with --no-dev but 5.6 fails both ways).

Do you want to change the readme?

**Comment by derschatta** [comment]
> @derschatta - This change drops out 5.6 install support (7.0+ can be installed with --no-dev but 5.6 fails both ways).
> 
> Do you want to change the readme?

ah right, I remember we talked about it. Yes, will update the Readme as well

**Comment by derschatta** [comment]
ok @codyfinegan , updated the readme. Could you have another look?

**Review by codyfinegan — APPROVED** [review]

**Comment by codyfinegan** [comment]
Looks good @derschatta

**Pull request merged**
